WITH date_spine AS (
    SELECT DATE_ADD('2024-01-01', INTERVAL seq DAY) AS full_date
    FROM (
        SELECT (a.a + (10 * b.a) + (100 * c.a) + (1000 * d.a)) AS seq
        FROM
            (SELECT 0 AS a UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a,
            (SELECT 0 AS a UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b,
            (SELECT 0 AS a UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) c,
            (SELECT 0 AS a UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) d
    ) numbers
    WHERE DATE_ADD('2024-01-01', INTERVAL seq DAY) <= '2026-12-31'
)

SELECT
    full_date,
    DAY(full_date) AS day,
    MONTH(full_date) AS month,
    QUARTER(full_date) AS quarter,
    YEAR(full_date) AS year,
    DAYNAME(full_date) AS day_of_week
FROM date_spine